services:
  app:
    container_name: employee-app
    image: cutlery47/employee-image:latest
    build:
      context: .
      tags:
      - "employee-image:latest"
    env_file: '.env'
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    volumes:
      - './${LOGGER_DIR}:/app/logs'
    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${POSTGRES_HOST}
    image: postgres:latest
    expose:
      - ${POSTGRES_PORT}
    env_file: '.env'
    volumes:
      - "postgres_storage:/var/lib/postgresql/data"
    restart: unless-stopped
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 5s
      timeout: 5s
      retries: 3

volumes:
  postgres_storage:
    driver: local